<?php

namespace Database\Seeders;

use App\Models\ApplicantProfile;
use App\Models\Application;
use App\Models\Company;
use App\Models\JobListing;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class RealJobsSeeder extends Seeder
{
    public function run(): void
    {
        // Clean wiping of old dummy data in safe relational order (Postgres/MySQL/SQLite compatible)
        Application::query()->delete();
        JobListing::query()->delete();
        Company::query()->delete();

        // Ensure primary demo applicant (Budi) exists
        $budi = User::firstOrCreate(
            ['email' => 'budi@demo.com'],
            [
                'name'          => 'Budi Santoso',
                'password'      => Hash::make('password'),
                'role'          => 'applicant',
                'nik'           => '3402011505010001',
                'whatsapp'      => '081234567890',
                'date_of_birth' => '2001-05-15',
            ]
        );

        ApplicantProfile::updateOrCreate(
            ['user_id' => $budi->id],
            [
                'whatsapp'              => '081234567890',
                'education_level'       => 'sma',
                'education_institution' => 'SMAN 3 Yogyakarta',
                'field_of_study'        => 'IPS',
                'work_experience'       => "1. Kasir Minimarket (1 tahun)\n2. Pramusaji Restoran (6 bulan)",
                'skills'                => ['Pelayanan pelanggan', 'Kasir', 'MS Excel', 'Komunikasi'],
                'salary_expectation'    => 'Rp2.500.000 – Rp3.500.000',
                'contact_email'         => 'budi@demo.com',
                'city'                  => 'Malang',
                'latitude'              => -7.9696,
                'longitude'             => 112.6312,
                'is_active'             => true,
                'application_credits'   => 5,
            ]
        );

        // Real Job Data from Google Spreadsheet (30 real listings from Malang & Yogyakarta)
        $jobs = [
            [
                'company_name'   => 'Adira Finance Malang 2 CAR',
                'owner_name'     => 'Raihan (HRD)',
                'address'        => 'Jl. Jaksa Agung Suprapto No.56, Rampal Celaket, Kec. Klojen, Kota Malang, Jawa Timur',
                'city'           => 'Malang',
                'latitude'       => -7.9696,
                'longitude'      => 112.6312,
                'business_field' => 'finance',
                'whatsapp'       => '6285925963965',
                'contact_email'  => 'rekrutmen.jatim@adira.co.id',
                'position'       => 'Remedial Officer',
                'category'       => 'sales',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 3,
                'salary_min'     => 2800000,
                'salary_max'     => 4000000,
                'qualifications' => "• Min. SMA/SMK sederajat\n• Punya kendaraan pribadi & SIM C aktif\n• Siap mobilitas tinggi di wilayah Malang\n• Komunikatif, mampu negosiasi, dan berorientasi target\n• BI Checking baik, jujur, disiplin, berintegritas",
                'description'    => "Bertanggung jawab dalam pengelolaan penagihan dan penyelesaian piutang pembiayaan kendaraan konsumen, melakukan kunjungan langsung secara persuasif, menjaga hubungan baik dengan nasabah, dan mencapai target pemulihan aset perusahaan.",
                'benefits'       => "Gaji pokok UMK, insentif performa bulanan, BPJS Kesehatan & Ketenagakerjaan, serta jenjang karier nasional terbuka lebar.",
                'howto_apply'    => "Walk-in Interview: Setiap hari kerja 09.00-12.00 WIB. Membawa Surat Lamaran, CV, FC KTP, KK, Ijazah, dan SIM C aktif.",
            ],
            [
                'company_name'   => 'Lucky Store Malang',
                'owner_name'     => 'Store Manager Lucky',
                'address'        => 'Jl. Soekarno Hatta No.86A, Mojolangu, Kota Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9427,
                'longitude'      => 112.6175,
                'business_field' => 'retail',
                'whatsapp'       => '6285113647518',
                'contact_email'  => 'luckystore.mlg@gmail.com',
                'position'       => 'Shopkeeper / Penjaga Toko',
                'category'       => 'retail',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 2,
                'salary_min'     => 2100000,
                'salary_max'     => 2600000,
                'qualifications' => "• Pria/Wanita, domisili Malang\n• Bertanggung jawab, jujur, dan ramah\n• Tidak sedang menempuh kuliah\n• Paham penggunaan smartphone dan sistem POS kasir\n• Bersedia bekerja sistem shift (8 jam/hari)",
                'description'    => "Melayani pelanggan yang berbelanja, mencatat transaksi penjualan kasir, menata stok barang di etalase, dan menjaga kebersihan serta kerapian toko.",
                'benefits'       => "Gaji pokok, bonus penjualan bulanan, dan libur 1 hari per minggu.",
                'howto_apply'    => "Kirim CV dan foto terbaru via WhatsApp ke 0851-1364-7518.",
            ],
            [
                'company_name'   => 'Caw Eatery Malang',
                'owner_name'     => 'Management Caw Eatery',
                'address'        => 'Jl. Ters. Wijaya Kusuma Atas No.34, Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9492,
                'longitude'      => 112.6288,
                'business_field' => 'fnb',
                'whatsapp'       => '6285194565458',
                'contact_email'  => 'caw.eatery@gmail.com',
                'position'       => 'Kitchen Crew / Kitchen Helper',
                'category'       => 'fnb',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 3,
                'salary_min'     => 1900000,
                'salary_max'     => 2400000,
                'qualifications' => "• Pria/Wanita, min. SMA/SMK sederajat\n• Punya kendaraan pribadi\n• Jujur, disiplin, ramah, dan cekatan\n• Bersedia bekerja di lingkungan dapur resto\n• Mampu bekerja sama dalam tim",
                'description'    => "Membantu persiapan bahan masakan (prep work), memasak pesanan sesuai SOP resep, menjaga standar kebersihan dan sanitasi area kitchen, serta stock opname bahan harian.",
                'benefits'       => "Makan gratis per shift, seragam, tips harian, dan bonus omset.",
                'howto_apply'    => "Kirim CV via WhatsApp atau email caw.eatery@gmail.com (Subjek: TimKitchen_NomorHP_Nama).",
            ],
            [
                'company_name'   => 'Kantor Notaris-PPAT M. Haris Fathony, S.H., M.Kn',
                'owner_name'     => 'M. Haris Fathony, S.H.',
                'address'        => 'Jl. KH. Zainul Arifin No. 3A, Kota Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9863,
                'longitude'      => 112.6322,
                'business_field' => 'jasa',
                'whatsapp'       => '628125224615',
                'contact_email'  => 'kenshiny2j@gmail.com',
                'position'       => 'Staff Administrasi Lapangan',
                'category'       => 'administrasi',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 2,
                'salary_min'     => 2200000,
                'salary_max'     => 2800000,
                'qualifications' => "• Perempuan, min. SMA/sederajat\n• Menguasai MS Word dan Excel dengan baik\n• Mampu bekerja tim maupun mandiri\n• Ulet, pekerja keras, teliti, dan bertanggung jawab\n• Memiliki kendaraan dan SIM C aktif",
                'description'    => "Mengurus administrasi berkas kenotariatan dan PPAT, pengecekan berkas ke instansi terkait (BPN/Dispenda), pengarsipan data akta, dan korespondensi dokumen klien.",
                'benefits'       => "Gaji bulanan, uang transport/bensin lapangan, dan pengalaman berharga di bidang hukum/kenotariatan.",
                'howto_apply'    => "Kirim CV dan berkas lamaran ke kenshiny2j@gmail.com atau WA 08125224615.",
            ],
            [
                'company_name'   => 'Smart Wash Laundry',
                'owner_name'     => 'Ibu Wahyuni',
                'address'        => 'Jl. Raya Cengger Ayam No. 30, Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9458,
                'longitude'      => 112.6245,
                'business_field' => 'jasa',
                'whatsapp'       => '6285755500885',
                'contact_email'  => 'lowkerhallo@gmail.com',
                'position'       => 'Staff Laundry & Setrika',
                'category'       => 'jasa',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 2,
                'salary_min'     => 1800000,
                'salary_max'     => 2300000,
                'qualifications' => "• Wanita, usia maksimal 35 tahun\n• Sehat jasmani dan rohani\n• Jujur, rajin, rapi, dan bertanggung jawab\n• Pengalaman laundry menjadi nilai tambah (pemula dipersilakan)\n• Bersedia bekerja sistem shift",
                'description'    => "Mencuci, mengeringkan, menyetrika uap dengan rapi, melakukan packing pakaian pelanggan, dan melayani penerimaan serta pengambilan pakaian.",
                'benefits'       => "Fasilitas mess/kamar tinggal, jatah sembako bulanan, dan bonus lembur.",
                'howto_apply'    => "Hubungi via WhatsApp 0857-5550-0885 atau kirim email ke lowkerhallo@gmail.com.",
            ],
            [
                'company_name'   => 'Showroom AMA Jaya Mobil',
                'owner_name'     => 'Bapak Supardi',
                'address'        => 'Jl. Raya Kebonsari No. 448, Tumpang, Kab. Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9984,
                'longitude'      => 112.7533,
                'business_field' => 'otomotif',
                'whatsapp'       => '6285700800190',
                'contact_email'  => 'amajayamobil@gmail.com',
                'position'       => 'Staff Showroom & Front Office',
                'category'       => 'otomotif',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 2,
                'salary_min'     => 2000000,
                'salary_max'     => 2700000,
                'qualifications' => "• Wanita, usia maksimal 35 tahun\n• Jujur, disiplin, tepat waktu\n• Ramah, sopan, komunikatif, berpenampilan rapi\n• Mampu bekerja sama dalam tim",
                'description'    => "Menyambut calon pembeli yang datang ke showroom, mencatat database konsumen, membantu pendataan unit kendaraan masuk dan keluar, serta melayani administrasi umum showroom.",
                'benefits'       => "Gaji pokok, insentif unit terjual, dan bonus akhir tahun.",
                'howto_apply'    => "Kirim CV langsung via WhatsApp ke 085700800190.",
            ],
            [
                'company_name'   => 'Collins Group (Collins Food & Beverage)',
                'owner_name'     => 'HR Collins Group',
                'address'        => 'Perum BTU Blok UJ 35, Madyopuro, Kota Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9803,
                'longitude'      => 112.6685,
                'business_field' => 'fnb',
                'whatsapp'       => '62881027405381',
                'contact_email'  => 'collinsgroupid@gmail.com',
                'position'       => 'Kitchen Crew / Kasir & Barista',
                'category'       => 'fnb',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 4,
                'salary_min'     => 1800000,
                'salary_max'     => 2300000,
                'qualifications' => "• Pengalaman di industri F&B menjadi nilai plus\n• Kuat dalam operasional harian dan problem-solving\n• Memiliki passion terhadap hospitality dan pelayanan yang ramah",
                'description'    => "Meracik minuman atau mengolah hidangan sesuai pesanan tiket, melayani transaksi kasir secara ramah, dan menjaga standar kualitas produk Collins Group.",
                'benefits'       => "Gaji pokok, insentif kehadiran, pelatihan barista & hospitality bersertifikat internal.",
                'howto_apply'    => "Kirimkan CV ke collinsgroupid@gmail.com atau chat WhatsApp 0881027405381.",
            ],
            [
                'company_name'   => 'Indy Vapors Malang',
                'owner_name'     => 'Owner Indy Vapors',
                'address'        => 'Jl. Andong Selatan 1F, Kota Malang (area Soekarno Hatta)',
                'city'           => 'Malang',
                'latitude'       => -7.9431,
                'longitude'      => 112.6189,
                'business_field' => 'retail',
                'whatsapp'       => '628971688876',
                'contact_email'  => 'indyvapors.id@gmail.com',
                'position'       => 'Admin Toko & Inventory',
                'category'       => 'retail',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 1,
                'salary_min'     => 2000000,
                'salary_max'     => 2500000,
                'qualifications' => "• Pria/Wanita, usia min. 21 tahun\n• Min. SMA/SMK/sederajat\n• Jujur, rapi, disiplin, attitude baik\n• Percaya diri, komunikatif, dan mampu kerja tim",
                'description'    => "Pencatatan & rekap keuangan harian, pengelolaan stok barang masuk dan keluar, stock opname rutin mingguan, serta administrasi umum toko.",
                'benefits'       => "Gaji tetap bulanan, potongan harga produk karyawan, dan bonus target toko.",
                'howto_apply'    => "Kirim CV dan berkas lamaran ke WhatsApp 0897-1688-876.",
            ],
            [
                'company_name'   => 'PT. Cahaya Unggul Abadi Nawasena',
                'owner_name'     => 'Ibu Dewi (HRD)',
                'address'        => 'Jl. Raya Kendalpayak 9B, Watudakon, Pakisaji, Kab. Malang, Jawa Timur',
                'city'           => 'Malang',
                'latitude'       => -8.0487,
                'longitude'      => 112.6234,
                'business_field' => 'manufaktur',
                'whatsapp'       => '628113898987',
                'contact_email'  => 'hrd.ptcuan@gmail.com',
                'position'       => 'Staff Accounting & Pajak',
                'category'       => 'administrasi',
                'work_type'      => 'full_time',
                'min_education'  => 's1',
                'quota'          => 1,
                'salary_min'     => 3200000,
                'salary_max'     => 4500000,
                'qualifications' => "• Pria/Wanita, usia maksimal 35 tahun\n• Pendidikan minimal S1 Akuntansi\n• Memahami sistem Coretax, PPh 21/23, dan PPN\n• Diutamakan memiliki sertifikat Brevet A & B\n• Terbiasa menyusun jurnal umum, buku besar, dan laporan keuangan perusahaan",
                'description'    => "Menyusun pembukuan keuangan harian, rekonsiliasi bank, penghitungan dan pelaporan pajak bulanan serta tahunan perusahaan manufaktur.",
                'benefits'       => "Gaji pokok kompetitif, BPJS Kesehatan & Ketenagakerjaan, tunjangan hari raya (THR), dan makan siang.",
                'howto_apply'    => "Kirim CV lengkap dan transkrip nilai ke hrd.ptcuan@gmail.com atau hubungi Bu Dewi di 0811-3898-987.",
            ],
            [
                'company_name'   => 'Gangnam Chicken by Mr.Nam',
                'owner_name'     => 'Mr. Nam / Operational HR',
                'address'        => 'Jl. Simpang Wilis C2, Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9734,
                'longitude'      => 112.6190,
                'business_field' => 'fnb',
                'whatsapp'       => '628113661908',
                'contact_email'  => 'gangnamchicken.mlg@gmail.com',
                'position'       => 'Cook / Cook Helper Korean Food',
                'category'       => 'fnb',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 3,
                'salary_min'     => 1800000,
                'salary_max'     => 3000000,
                'qualifications' => "• Pria/Wanita, disiplin dan tahan bekerja di bawah tekanan tinggi\n• Memiliki ketertarikan tinggi pada masakan Korea\n• Menjaga standar kebersihan masakan dan area kerja",
                'description'    => "Memasak menu ayam khas Korea (fried chicken, sauces, side dish) sesuai SOP takaran rasa Mr. Nam, mengoperasikan deep fryer, dan mengontrol stok bahan baku harian.",
                'benefits'       => "Gaji Rp1,8 - Rp3 juta++, bonus omset Rp50.000 - Rp500.000+/bulan, makan gratis setiap hari kerja, dan THR.",
                'howto_apply'    => "Kirim berkas lamaran dan CV via WhatsApp ke 08113661908.",
            ],
            [
                'company_name'   => 'Haven Light Clinic Malang',
                'owner_name'     => 'Manajemen Haven Light',
                'address'        => 'Jl. Buring 29, Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9754,
                'longitude'      => 112.6291,
                'business_field' => 'kesehatan',
                'whatsapp'       => '6285777710399',
                'contact_email'  => 'career@havenlightclinic.com',
                'position'       => 'Asisten Apoteker Klinis',
                'category'       => 'kesehatan',
                'work_type'      => 'full_time',
                'min_education'  => 'd3',
                'quota'          => 2,
                'salary_min'     => 2600000,
                'salary_max'     => 3500000,
                'qualifications' => "• Pria/Wanita, usia maksimal 35 tahun\n• Minimal D3 Farmasi dengan STRTTK aktif\n• Jujur, teliti, ramah, dan sopan kepada pasien\n• Memahami etiket obat kecantikan dan estetika medis",
                'description'    => "Melayani peracikan resep obat dari dokter estetika, menjelaskan dosis dan cara pakai ke pasien, mengelola stok obat klinik, dan pengawasan kadaluarsa.",
                'benefits'       => "Gaji pokok UMR, insentif pelayanan obat, diskon treatment estetika klinik gratis/karyawan, dan BPJS.",
                'howto_apply'    => "Kirimkan CV dan surat lamaran langsung ke alamat klinik atau chat WA 085.7777.10399.",
            ],
            [
                'company_name'   => 'Rumah Sakit Prasetya Husada',
                'owner_name'     => 'Bagian Rekrutmen RS Prasetya Husada',
                'address'        => 'Jl. Raya Ngijo 25, Karangploso, Kab. Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9023,
                'longitude'      => 112.5991,
                'business_field' => 'kesehatan',
                'whatsapp'       => '6285173230558',
                'contact_email'  => 'rekrutmen.rsprasetyahusada@gmail.com',
                'position'       => 'Perawat Rawat Inap / Bidan / Kasir Medis',
                'category'       => 'kesehatan',
                'work_type'      => 'full_time',
                'min_education'  => 'd3',
                'quota'          => 5,
                'salary_min'     => 2800000,
                'salary_max'     => 4200000,
                'qualifications' => "• D3/S1 Keperawatan/Kebidanan (STR aktif) untuk tenaga perawat\n• Min. SMA/D3 untuk Kasir & Administrasi\n• Berorientasi pada keselamatan pasien dan ramah melayani",
                'description'    => "Memberikan asuhan keperawatan profesional di instalasi rawat inap dan rawat jalan RS, atau melakukan pelayanan administrasi pembayaran pasien bagi posisi kasir.",
                'benefits'       => "Gaji pokok, jasa medis, BPJS Ketenagakerjaan & Kesehatan, seragam RS, dan pelatihan ber-SKP.",
                'howto_apply'    => "Kirim lamaran via email ke rekrutmen.rsprasetyahusada@gmail.com dengan subjek: Nama_Posisi yang dilamar.",
            ],
            [
                'company_name'   => 'Piring Asia Digital',
                'owner_name'     => 'Marketing Lead Piring Asia',
                'address'        => 'Jl. Wilis No.11, Malang (Kota Malang, Jawa Timur)',
                'city'           => 'Malang',
                'latitude'       => -7.9731,
                'longitude'      => 112.6185,
                'business_field' => 'teknologi',
                'whatsapp'       => '628974324894',
                'contact_email'  => 'marketing.piringasia@gmail.com',
                'position'       => 'Content Creator (Paid Internship)',
                'category'       => 'teknologi',
                'work_type'      => 'internship',
                'min_education'  => 'sma',
                'quota'          => 2,
                'salary_min'     => 1200000,
                'salary_max'     => 1700000,
                'qualifications' => "• Tertarik pada social media & content creation F&B\n• Memahami tren TikTok, Instagram Reels, dan visual feed\n• Mampu shooting dasar dengan smartphone\n• Punya taste visual yang menarik dan adaptif",
                'description'    => "Memproduksi konten video pendek harian (TikTok & Reels), riset tren viral kuliner, meliput hidangan dan event resto, serta evaluasi insight konten.",
                'benefits'       => "Uang saku bulanan, makan gratis di resto partner, sertifikat magang resmi, dan bimbingan mentor berpengalaman.",
                'howto_apply'    => "Kirim CV & Portofolio ke marketing.piringasia@gmail.com (Subjek: Content Creator_Nama) atau WA 0897-4324-894.",
            ],
            [
                'company_name'   => 'Tlogondalem by Tlogondalem Group',
                'owner_name'     => 'Manager Tlogondalem',
                'address'        => 'Jl. Raya Tlogowaru No. 8, Malang',
                'city'           => 'Malang',
                'latitude'       => -8.0289,
                'longitude'      => 112.6512,
                'business_field' => 'fnb',
                'whatsapp'       => '6281125507778',
                'contact_email'  => 'tlogondalem.group@gmail.com',
                'position'       => 'Kasir / Waiter / Cook',
                'category'       => 'fnb',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 3,
                'salary_min'     => 1900000,
                'salary_max'     => 2600000,
                'qualifications' => "• Kasir: Wanita, usia max 28th, min SMA/SMK, teliti, menguasai komputer\n• Waiter: Pria, usia max 28th, komunikatif, cekatan\n• Cook: Pria/Wanita, usia max 30th, berpengalaman memasak",
                'description'    => "Menjalankan operasional restoran sesuai divisi: melayani pesanan tamu (waiter), transaksi kasir dan billing (kasir), atau memasak masakan nusantara (cook).",
                'benefits'       => "Gaji bulanan, makan gratis, uang lembur, dan suasana resto asri khas tradisional Jawa.",
                'howto_apply'    => "Kirim lamaran via WhatsApp ke 0811 2550 7778.",
            ],
            [
                'company_name'   => 'Céladiné Food Malang',
                'owner_name'     => 'Ibu Celadine',
                'address'        => 'Jl. Sigura Gura Barat No. 15, Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9572,
                'longitude'      => 112.6073,
                'business_field' => 'fnb',
                'whatsapp'       => '6285785030838',
                'contact_email'  => 'celadinefood@gmail.com',
                'position'       => 'Staff Part-Time Booth Salad Sayur',
                'category'       => 'fnb',
                'work_type'      => 'part_time',
                'min_education'  => 'sma',
                'quota'          => 2,
                'salary_min'     => 1200000,
                'salary_max'     => 1600000,
                'qualifications' => "• Wanita, usia 20-30 tahun\n• Cekatan, bersih, bertanggung jawab\n• Memiliki sepeda motor sendiri\n• Tidak sedang kuliah aktif",
                'description'    => "Menjaga booth salad sayur buah sehat di area Sigura-gura, melayani pembeli, memotong dan menata salad segar, mencatat penjualan harian, dan menjaga kebersihan booth. Pilihan shift: 07.00-14.00 atau 14.00-21.00.",
                'benefits'       => "Gaji part time, bonus omset harian, dan libur 1x dalam seminggu.",
                'howto_apply'    => "Hubungi via WhatsApp di nomor 085785030838.",
            ],
            [
                'company_name'   => 'Gaharu Massage Malang',
                'owner_name'     => 'Manager Gaharu',
                'address'        => 'Jl. LA Sucipto Gang 22A No. 48, Kec. Blimbing, Kota Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9532,
                'longitude'      => 112.6541,
                'business_field' => 'jasa',
                'whatsapp'       => '6281337063152',
                'contact_email'  => 'gaharumassagemalang@gmail.com',
                'position'       => 'Staff Admin Reservasi',
                'category'       => 'administrasi',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 2,
                'salary_min'     => 1400000,
                'salary_max'     => 2000000,
                'qualifications' => "• Wanita, usia maksimal 27 tahun\n• Min. SMA/SMK\n• Bisa mengoperasikan MS Word dan Excel\n• Cekatan, teliti, dan ramah\n• Tidak sedang kuliah aktif",
                'description'    => "Mencatat reservasi jadwal klien pijat dan refleksi, mengatur jadwal terapis, menyusun laporan keuangan harian, dan melayani pelanggan dengan sopan.",
                'benefits'       => "Gaji pokok Rp1.200.000 + bonus pengerjaan + lembur, serta BPJS Ketenagakerjaan.",
                'howto_apply'    => "Kirim CV ke WhatsApp 0813-3706-3152 atau email gaharumassagemalang@gmail.com.",
            ],
            [
                'company_name'   => 'Zoo Laundry Merjosari',
                'owner_name'     => 'Bapak Andrean',
                'address'        => 'Jl. Joyosari No. 67 (Merjosari), Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9409,
                'longitude'      => 112.5978,
                'business_field' => 'jasa',
                'whatsapp'       => '6282261610016',
                'contact_email'  => 'zoolaundry.mlg@gmail.com',
                'position'       => 'Staff Laundry & Setrika Uap',
                'category'       => 'jasa',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 2,
                'salary_min'     => 1700000,
                'salary_max'     => 2200000,
                'qualifications' => "• Wanita, usia maksimal 35 tahun\n• Rapi dan cekatan dalam menyetrika (ada pelatihan teknis)\n• Tepat waktu, bersih, rapi, berpenampilan bersih",
                'description'    => "Menyetrika pakaian dengan setrika uap industri, melipat pakaian secara presisi dan rapi, mengepak plastik laundry, serta menjaga kerapian outlet.",
                'benefits'       => "Gaji pokok bulanan, bonus target kiloan, dan libur 1 kali seminggu.",
                'howto_apply'    => "Kirim CV dan info diri via WhatsApp ke 0822-6161-0016.",
            ],
            [
                'company_name'   => 'Klinik Rawat Inap Tri Mulyo',
                'owner_name'     => 'Direksi Klinik Tri Mulyo',
                'address'        => 'Jl. Panglima Sudirman No. 1, Pagelaran, Kab. Malang',
                'city'           => 'Malang',
                'latitude'       => -8.2012,
                'longitude'      => 112.5921,
                'business_field' => 'kesehatan',
                'whatsapp'       => '628113371111',
                'contact_email'  => 'trimulyo2019@gmail.com',
                'position'       => 'Administrasi Rekam Medis & Pendaftaran',
                'category'       => 'administrasi',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 2,
                'salary_min'     => 2100000,
                'salary_max'     => 2700000,
                'qualifications' => "• Laki-laki/Perempuan, usia maksimal 28 tahun\n• Min. SMA/SMK sederajat\n• Mampu bekerja tim maupun mandiri\n• Bersedia bekerja dengan sistem shift klinik",
                'description'    => "Mendaftarkan pasien rawat jalan dan rawat inap, mengelola file rekam medis, input klaim BPJS Kesehatan, dan penyusunan laporan kunjungan pasien harian.",
                'benefits'       => "Gaji pokok, insentif shift malam, BPJS, dan jenjang karier di fasilitas kesehatan terakreditasi.",
                'howto_apply'    => "Kirimkan berkas lamaran ke trimulyo2019@gmail.com atau WA 0811 337 1111.",
            ],
            [
                'company_name'   => 'CV. Duta Beton Group',
                'owner_name'     => 'Pimpinan CV Duta Beton',
                'address'        => 'Jl. Raya Ngijo No. 282, Karangploso, Kab. Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9045,
                'longitude'      => 112.5982,
                'business_field' => 'konstruksi',
                'whatsapp'       => '6282132132507',
                'contact_email'  => 'infocvdutabeton@gmail.com',
                'position'       => 'Sales Marketing Lapangan',
                'category'       => 'sales',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 3,
                'salary_min'     => 2500000,
                'salary_max'     => 4500000,
                'qualifications' => "• Pria, berpenampilan sopan & komunikatif\n• Mampu bernegosiasi dan punya pengalaman sales bahan bangunan/proyek\n• Sehat jasmani dan rohani, jujur, amanah",
                'description'    => "Memasarkan produk beton cor, paving, dan precast ke kontraktor, mandor proyek, dan toko bangunan di area Malang Raya dan sekitarnya.",
                'benefits'       => "Gaji pokok, uang operasional harian, dan bonus komisi persentase omset yang tinggi.",
                'howto_apply'    => "Kirim berkas CV ke WA 082-132-132-507 atau email infocvdutabeton@gmail.com.",
            ],
            [
                'company_name'   => 'Nasi Kapau Abah Rantau',
                'owner_name'     => 'Abah Rantau',
                'address'        => 'Jl. Panglima Sudirman No. 116, Kesatrian, Malang (sebelah POM BP Rampal)',
                'city'           => 'Malang',
                'latitude'       => -7.9812,
                'longitude'      => 112.6394,
                'business_field' => 'fnb',
                'whatsapp'       => '6282142688484',
                'contact_email'  => 'abahrantau.kapau@gmail.com',
                'position'       => 'Kasir Resto (Freelance / Part Time)',
                'category'       => 'fnb',
                'work_type'      => 'harian',
                'min_education'  => 'sma',
                'quota'          => 2,
                'salary_min'     => 1100000,
                'salary_max'     => 1600000,
                'qualifications' => "• Pria/Wanita, jujur, teliti dalam berhitung uang\n• Menguasai mesin POS kasir\n• Berpenampilan rapi dan komunikatif melayani pelanggan",
                'description'    => "Melakukan input pesanan lauk Kapau ke sistem kasir, melayani pembayaran tunai/QRIS, serta membuat rekap penjualan tutup kasir harian.",
                'benefits'       => "Fee harian/mingguan, makan siang gratis masakan padang lezat, dan bonus lembur saat jam ramai.",
                'howto_apply'    => "Bawa CV langsung ke alamat resto atau hubungi WA 082142688484.",
            ],
            [
                'company_name'   => 'Citra Online Media Malang',
                'owner_name'     => 'Pimpinan Redaksi Citra',
                'address'        => 'Perumahan Havana Park Kav. H-20, Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9256,
                'longitude'      => 112.6012,
                'business_field' => 'teknologi',
                'whatsapp'       => '6285188372299',
                'contact_email'  => 'lowongancitraonlinemedia@gmail.com',
                'position'       => 'Admin Sosial Media & Content Design',
                'category'       => 'teknologi',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 2,
                'salary_min'     => 1500000,
                'salary_max'     => 2200000,
                'qualifications' => "• Wanita, belum menikah, min. SMA/SMK\n• Semangat kerja tinggi dan mau belajar hal baru\n• Menguasai Canva, CapCut/Kinemaster dasar\n• Terbuka untuk fresh graduate pemula",
                'description'    => "Membuat konten visual dan video feed Instagram/TikTok, membalas komentar dan DM audiens, riset topik yang sedang tren, dan menyusun jadwal postingan harian.",
                'benefits'       => "Masa percobaan Rp1,5 juta/bln, setelah lolos naik Rp1,8 - Rp2,2 juta + bonus performa konten viral.",
                'howto_apply'    => "Kirim CV & portofolio desain ke lowongancitraonlinemedia@gmail.com atau WA 0851-8837-2299.",
            ],
            [
                'company_name'   => 'Apotek Kartini Kromengan',
                'owner_name'     => 'Ibu Ningrum (Penanggung Jawab)',
                'address'        => 'Jl. Raya Ngadirejo No. 34, Ngadirejo, Kec. Kromengan, Kab. Malang',
                'city'           => 'Malang',
                'latitude'       => -8.0854,
                'longitude'      => 112.4921,
                'business_field' => 'kesehatan',
                'whatsapp'       => '6282148487828',
                'contact_email'  => 'ningrumkd@gmail.com',
                'position'       => 'Tenaga Teknis Kefarmasian (TTK)',
                'category'       => 'kesehatan',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 1,
                'salary_min'     => 2000000,
                'salary_max'     => 2600000,
                'qualifications' => "• Laki-laki/Perempuan, lulusan SMK Farmasi / D3 Farmasi\n• Usia 18-25 tahun\n• Jujur, komunikatif, dan memiliki skill melayani pasien\n• Teliti dalam membaca etiket resep",
                'description'    => "Melayani pembelian obat bebas dan resep dokter, memberikan informasi aturan minum obat ke pasien, mendata stok obat di rak, dan membuat laporan obat harian.",
                'benefits'       => "Gaji pokok, bonus penjualan suplemen, dan lingkungan kerja kekeluargaan yang nyaman.",
                'howto_apply'    => "Hubungi Ibu Ningrum di 082148487828 atau kirim berkas ke ningrumkd@gmail.com.",
            ],
            [
                'company_name'   => 'Masakan Padang Ampera Dep Pasca',
                'owner_name'     => 'Bapak Hendra',
                'address'        => 'Jl. MT Haryono No. 91, Kota Malang (depan Pascasarjana)',
                'city'           => 'Malang',
                'latitude'       => -7.9482,
                'longitude'      => 112.6133,
                'business_field' => 'fnb',
                'whatsapp'       => '6285336595667',
                'contact_email'  => 'amperadeppasca@gmail.com',
                'position'       => 'Karyawati Rumah Makan Padang',
                'category'       => 'fnb',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 2,
                'salary_min'     => 1800000,
                'salary_max'     => 2400000,
                'qualifications' => "• Wanita usia 18-30 tahun, min. pendidikan SMP\n• Jujur, disiplin, cekatan, dan ramah\n• Memakai kerudung dan mampu bekerja di lingkungan dinamis",
                'description'    => "Menyiapkan piring hidangan lauk, melayani pesanan bungkus dan makan di tempat para mahasiswa/umum, menjaga kebersihan meja, dan membantu kasir.",
                'benefits'       => "Gaji pokok, bonus harian, makan 3x sehari gratis, dan disediakan tempat tinggal/kamar tidur.",
                'howto_apply'    => "Hubungi langsung nomor kontak 0853 3659 5667 via telepon atau WhatsApp.",
            ],
            [
                'company_name'   => 'The Grove Cafe by Kaizen Group',
                'owner_name'     => 'Recruitment Kaizen Group',
                'address'        => 'Jl. Wilis No. 25, Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9739,
                'longitude'      => 112.6179,
                'business_field' => 'fnb',
                'whatsapp'       => '6285178903331',
                'contact_email'  => 'recruitment.kaizengroup@gmail.com',
                'position'       => 'Admin / General Affair Cafe',
                'category'       => 'administrasi',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 2,
                'salary_min'     => 2200000,
                'salary_max'     => 2800000,
                'qualifications' => "• Perempuan, pendidikan minimal SMA/SMK\n• Pengalaman di bidang administrasi resto/cafe menjadi nilai plus\n• Teliti dalam penginputan data keuangan dan pencatatan inventaris",
                'description'    => "Mengelola administrasi operasional cafe, purchase order bahan baku, absensi staf cafe, pembayaran vendor supplier, dan pembuatan laporan mingguan ke head office.",
                'benefits'       => "Gaji pokok, BPJS Ketenagakerjaan, bonus omset cafe, dan jenjang karier Kaizen Group.",
                'howto_apply'    => "Kirim CV & Surat Lamaran ke recruitment.kaizengroup@gmail.com (Subjek: Nama - AG - The Grove Cafe) atau WA 0851-7890-3331.",
            ],
            [
                'company_name'   => 'PT. Tiga Kru Kita',
                'owner_name'     => 'HRD PT Tiga Kru Kita',
                'address'        => 'Pondok Blimbing Indah Blok P6 No. 9, Kota Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9392,
                'longitude'      => 112.6514,
                'business_field' => 'logistik',
                'whatsapp'       => '6281234990037',
                'contact_email'  => 'tigakrukitapt@gmail.com',
                'position'       => 'General Admin (Part Time)',
                'category'       => 'administrasi',
                'work_type'      => 'part_time',
                'min_education'  => 'sma',
                'quota'          => 1,
                'salary_min'     => 1300000,
                'salary_max'     => 1800000,
                'qualifications' => "• Perempuan, usia 24-35 tahun\n• Komunikatif, ramah, menguasai Ms Office & Canva\n• Bisa entry data laporan Coretax & BPJS\n• Jam kerja part time 08.00 - 12.00 WIB",
                'description'    => "Membantu penginputan data pengiriman barang logistik, melayani customer service via chat, verifikasi berkas tagihan invoice, dan koordinasi internal kantor.",
                'benefits'       => "Gaji pokok part time proporsional, fleksibilitas waktu, dan tempat kerja ber-AC yang nyaman.",
                'howto_apply'    => "Apply via email tigakrukitapt@gmail.com atau telepon kantor 0812 3499 0037.",
            ],
            [
                'company_name'   => 'PT. Tiga Kru Kita Logistik',
                'owner_name'     => 'Koordinator Armada',
                'address'        => 'Pondok Blimbing Indah Blok P6 No. 9, Kota Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9392,
                'longitude'      => 112.6514,
                'business_field' => 'logistik',
                'whatsapp'       => '6281234990037',
                'contact_email'  => 'tigakrukitapt@gmail.com',
                'position'       => 'Driver Pengiriman Logistik (Full Time)',
                'category'       => 'logistik',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 2,
                'salary_min'     => 2600000,
                'salary_max'     => 3300000,
                'qualifications' => "• Laki-laki, usia 23-35 tahun\n• Memiliki SIM A / B1 aktif\n• Bisa mengendarai armada box L300 / truk engkel manual\n• Bersedia bantu bongkar muat, jujur, rajin, dan tidak merokok saat berkendara",
                'description'    => "Mengemudikan kendaraan box untuk pengiriman barang paket dari gudang ke agen-agen distributor di area Malang Raya, memastikan keutuhan barang dan ketepatan waktu.",
                'benefits'       => "Gaji pokok, uang jalan/makan harian, insentif ritase pengiriman, dan BPJS Ketenagakerjaan.",
                'howto_apply'    => "Kirim CV atau hubungi via WhatsApp 0812 3499 0037.",
            ],
            [
                'company_name'   => 'Toko Aster Malang (Kosmetik & Retail)',
                'owner_name'     => 'HRD Aster Kosmetik Group',
                'address'        => 'Jl. Agus Salim No. 44, Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9892,
                'longitude'      => 112.6318,
                'business_field' => 'retail',
                'whatsapp'       => '6285923503319',
                'contact_email'  => 'hrdastergroup@gmail.com',
                'position'       => 'Helper Packing Marketplace & Gudang',
                'category'       => 'retail',
                'work_type'      => 'part_time',
                'min_education'  => 'sma',
                'quota'          => 3,
                'salary_min'     => 1300000,
                'salary_max'     => 1900000,
                'qualifications' => "• Pria/Wanita, pendidikan minimal SMP/SMA\n• Cekatan, teliti dengan nomor resi pesanan online\n• Mampu bekerja cepat mencapai target packing harian",
                'description'    => "Mengambil produk kosmetik sesuai list pesanan marketplace (Shopee/Tokopedia), membungkus dengan bubble wrap tebal, menempel resi, dan serah terima ke kurir ekspedisi.",
                'benefits'       => "Gaji pokok, bonus target jumlah paket, dan diskon belanja produk perawatan kulit.",
                'howto_apply'    => "Kirim lamaran langsung ke Toko Aster Malang (tulis 'Helper Packing MP' di pojok amplop) atau via email hrdastergroup@gmail.com.",
            ],
            [
                'company_name'   => 'HokBen Soehat Malang',
                'owner_name'     => 'Store Manager HokBen',
                'address'        => 'Jl. Soekarno Hatta No. D401, Mojolangu, Lowokwaru, Kota Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9419,
                'longitude'      => 112.6171,
                'business_field' => 'fnb',
                'whatsapp'       => '6281234567800',
                'contact_email'  => 'recruitment@hokben.co.id',
                'position'       => 'Crew Restaurant Part Time',
                'category'       => 'fnb',
                'work_type'      => 'part_time',
                'min_education'  => 'sma',
                'quota'          => 4,
                'salary_min'     => 1400000,
                'salary_max'     => 1900000,
                'qualifications' => "• Belum menikah, min. SMA/SMK sederajat\n• Tidak berkacamata dan mata tidak minus/silinder\n• Tidak bertato dan tidak bertindik bagi pria\n• Memiliki komunikasi yang ramah dan siap kerja shift",
                'description'    => "Melayani pelanggan di counter pemesanan, menyiapkan paket bento khas HokBen, menjaga higienitas area makan dan kitchen sesuai standar restoran Jepang internasional.",
                'benefits'       => "Upah part time resmi, makan gratis menu HokBen saat shift, seragam lengkap, dan asuransi kecelakaan kerja.",
                'howto_apply'    => "Kirimkan lamaran lengkap ke alamat resto HokBen Soehat atau email recruitment@hokben.co.id (Subjek: Crew - Malang).",
            ],
            [
                'company_name'   => 'Wuling Perdana Jatim (Wuling Motors)',
                'owner_name'     => 'Ibu Luki (Supervisor)',
                'address'        => 'Jl. Letjen Sutoyo No. 6, Malang',
                'city'           => 'Malang',
                'latitude'       => -7.9621,
                'longitude'      => 112.6362,
                'business_field' => 'otomotif',
                'whatsapp'       => '6282111999071',
                'contact_email'  => 'sales.wulingjatim@gmail.com',
                'position'       => 'Sales Consultant Mobil Baru',
                'category'       => 'sales',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 3,
                'salary_min'     => 2600000,
                'salary_max'     => 6000000,
                'qualifications' => "• Pria/Wanita, min. SMA sederajat\n• Berpenampilan menarik, rapi, dan percaya diri\n• Memiliki SIM A aktif dan bisa menyetir mobil\n• Aktif media sosial dan orientasi pada target penjualan",
                'description'    => "Mempromosikan lini mobil Wuling (Alvez, Air EV, Binguo EV, Cortez) ke calon pembeli, mendampingi sesi test drive, mengurus simulasi kredit leasing, dan serah terima unit kendaraan.",
                'benefits'       => "Gaji pokok, insentif unit tidak terbatas, reward liburan ke luar negeri bagi top salesman, dan tunjangan operasional.",
                'howto_apply'    => "Kirim CV Anda ke alamat dealer Wuling Letjen Sutoyo atau via WhatsApp ke Ibu Luki di 0821 1199 9071.",
            ],
            // Real Yogyakarta jobs
            [
                'company_name'   => 'Kopi Titik Koma Malioboro',
                'owner_name'     => 'Manager Titik Koma Jogja',
                'address'        => 'Jl. Malioboro No. 45, Danurejan, Kota Yogyakarta',
                'city'           => 'Yogyakarta',
                'latitude'       => -7.7942,
                'longitude'      => 110.3659,
                'business_field' => 'fnb',
                'whatsapp'       => '6281392817263',
                'contact_email'  => 'jogja.titikkoma@gmail.com',
                'position'       => 'Barista & Cashier',
                'category'       => 'fnb',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 3,
                'salary_min'     => 2300000,
                'salary_max'     => 2900000,
                'qualifications' => "• Pria/Wanita, usia 19-27 tahun\n• Memiliki ketertarikan tinggi pada industri kopi\n• Ramah, teliti mengoperasikan mesin espresso dan kasir\n• Siap bekerja sistem shifting",
                'description'    => "Menyiapkan aneka racikan kopi artisan dan non-kopi, melayani pemesanan pengunjung Malioboro, menjaga kebersihan bar station, dan stock opname biji kopi harian.",
                'benefits'       => "Gaji UMR Jogja, uang tips mingguan, jatah kopi karyawan gratis, dan pelatihan barista.",
                'howto_apply'    => "Kirim CV ke WhatsApp 0813-9281-7263 atau email jogja.titikkoma@gmail.com.",
            ],
            [
                'company_name'   => 'Batik Keraton Yogyakarta',
                'owner_name'     => 'Ibu Sekar Arum',
                'address'        => 'Jl. Wijilan No. 12, Panembahan, Kraton, Kota Yogyakarta',
                'city'           => 'Yogyakarta',
                'latitude'       => -7.8041,
                'longitude'      => 110.3688,
                'business_field' => 'retail',
                'whatsapp'       => '6282138475920',
                'contact_email'  => 'batikkeraton.jogja@gmail.com',
                'position'       => 'Pramuniaga Galeri Batik',
                'category'       => 'retail',
                'work_type'      => 'full_time',
                'min_education'  => 'sma',
                'quota'          => 2,
                'salary_min'     => 2200000,
                'salary_max'     => 2700000,
                'qualifications' => "• Wanita, usia 20-30 tahun, min. SMA/SMK\n• Berpenampilan sopan, anggun, dan ramah\n• Senang berkomunikasi dan menjelaskan motif batik ke wisatawan",
                'description'    => "Menyambut wisatawan lokal dan mancanegara yang berkunjung ke galeri batik, menjelaskan filosofi motif kain, melayani transaksi pembelian, dan menjaga kerapian etalase kain.",
                'benefits'       => "Gaji pokok, bonus komisi penjualan kain, seragam batik nusantara, dan libur mingguan.",
                'howto_apply'    => "Kirim CV melalui WhatsApp 0821-3847-5920 atau drop langsung ke galeri Wijilan.",
            ],
        ];

        foreach ($jobs as $idx => $item) {
            $userEmail = 'employer' . ($idx + 1) . '@nearjob.id';
            $companyUser = User::firstOrCreate(
                ['email' => $userEmail],
                [
                    'name'          => $item['owner_name'],
                    'password'      => Hash::make('password'),
                    'role'          => 'company',
                    'nik'           => '35730' . str_pad((string)($idx + 100), 11, '0', STR_PAD_LEFT),
                    'whatsapp'      => $item['whatsapp'],
                    'date_of_birth' => '1990-01-01',
                ]
            );

            $company = Company::create([
                'user_id'         => $companyUser->id,
                'owner_name'      => $item['owner_name'],
                'nik'             => $companyUser->nik,
                'whatsapp'        => $item['whatsapp'],
                'company_name'    => $item['company_name'],
                'business_field'  => $item['business_field'],
                'address'         => $item['address'],
                'city'            => $item['city'],
                'latitude'        => $item['latitude'],
                'longitude'       => $item['longitude'],
                'contact_email'   => $item['contact_email'],
                'contact_method'  => 'whatsapp',
                'agreed_to_terms' => true,
            ]);

            JobListing::create([
                'company_id'       => $company->id,
                'position'         => $item['position'],
                'description'      => $item['description'] . "\n\nBenefit: " . $item['benefits'] . "\n\nCara Melamar: " . $item['howto_apply'],
                'qualifications'   => $item['qualifications'],
                'city'             => $item['city'],
                'latitude'         => $item['latitude'],
                'longitude'        => $item['longitude'],
                'work_type'        => $item['work_type'],
                'job_category'     => $item['category'],
                'min_education'    => $item['min_education'],
                'radius_km'        => 35,
                'status'           => 'active',
                'salary_min'       => $item['salary_min'],
                'salary_max'       => $item['salary_max'],
                'quota'            => $item['quota'],
                'contact_whatsapp' => $item['whatsapp'],
                'contact_email'    => $item['contact_email'],
                'contact_method'   => 'whatsapp',
            ]);
        }
    }
}
